### ISSUE TITLE
You forgot to push the actual code.

### ISSUE THREAD

**Issue by bcdev-** [joostrijneveld/chacha-arm-cortex-m#1]
`make.mk` file references `../common/chacha20.s`, yet the file is missing.

Cheers! :wink:

**Comment by bcdev-** [comment]
Sorry, my utmost stupidity. :sunglasses: 
The code is there, I'm just blind.

Btw, thx! :heart:

**Comment by joostrijneveld** [comment]
I suppose a few extra sentences in the README wouldn't hurt, though!
